# core/document_engine.py
"""Unified document generation: DOCX, PDF, PPTX, XLSX."""

from __future__ import annotations
import os
from pathlib import Path


def _docx(content: str, title: str, output_path: str) -> str:
	from docx import Document
	from docx.shared import RGBColor

	doc = Document()
	h = doc.add_heading(title, level=0)
	if h.runs:
		h.runs[0].font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

	for line in content.split('\n'):
		line = line.rstrip()
		if line.startswith('### '):
			doc.add_heading(line[4:], level=3)
		elif line.startswith('## '):
			doc.add_heading(line[3:], level=2)
		elif line.startswith('# '):
			doc.add_heading(line[2:], level=1)
		elif line.startswith('- ') or line.startswith('* '):
			doc.add_paragraph(line[2:], style='List Bullet')
		elif line == '':
			continue
		else:
			doc.add_paragraph(line)

	doc.save(output_path)
	return output_path


def _pdf(content: str, title: str, output_path: str) -> str:
	from reportlab.lib.pagesizes import A4
	from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
	from reportlab.lib.units import cm
	from reportlab.lib.colors import HexColor
	from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

	doc = SimpleDocTemplate(
		output_path, pagesize=A4,
		leftMargin=2 * cm, rightMargin=2 * cm,
		topMargin=2.5 * cm, bottomMargin=2.5 * cm,
	)
	styles = getSampleStyleSheet()
	title_style = ParagraphStyle(
		'TitleStyle', parent=styles['Heading1'],
		textColor=HexColor('#1F497D'), fontSize=18, spaceAfter=12,
	)
	h1_style = ParagraphStyle('H1', parent=styles['Heading2'], fontSize=14, spaceAfter=8)
	h2_style = ParagraphStyle('H2', parent=styles['Heading3'], fontSize=12, spaceAfter=6)
	body_style = styles['Normal']

	story = [Paragraph(title, title_style), Spacer(1, 0.5 * cm)]

	for line in content.split('\n'):
		line = line.rstrip()
		if not line:
			story.append(Spacer(1, 0.2 * cm))
		elif line.startswith('## '):
			story.append(Paragraph(line[3:], h2_style))
		elif line.startswith('# '):
			story.append(Paragraph(line[2:], h1_style))
		elif line.startswith('- ') or line.startswith('* '):
			story.append(Paragraph(f'• {line[2:]}', body_style))
		else:
			story.append(Paragraph(line, body_style))

	doc.build(story)
	return output_path


def _pptx(content: str, title: str, output_path: str, slides: list[dict] | None = None) -> str:
	from pptx import Presentation

	prs = Presentation()
	title_layout = prs.slide_layouts[0]
	sl = prs.slides.add_slide(title_layout)
	sl.shapes.title.text = title
	sl.placeholders[1].text = 'Generated by Thuon Platform'

	content_layout = prs.slide_layouts[1]

	if slides:
		for s in slides:
			slide = prs.slides.add_slide(content_layout)
			slide.shapes.title.text = s.get('title', '')
			slide.placeholders[1].text_frame.text = s.get('content', '')
	else:
		current_title = ''
		current_body: list[str] = []

		def flush():
			if current_title or current_body:
				slide = prs.slides.add_slide(content_layout)
				slide.shapes.title.text = current_title or 'Slide'
				slide.placeholders[1].text_frame.text = '\n'.join(current_body)

		for line in content.split('\n'):
			line = line.rstrip()
			if line.startswith('#'):
				flush()
				current_title = line.lstrip('#').strip()
				current_body = []
			elif line:
				current_body.append(line)

		flush()

	prs.save(output_path)
	return output_path


def _xlsx(rows: list[dict], sheet_name: str, output_path: str) -> str:
	from openpyxl import Workbook
	from openpyxl.styles import Font, PatternFill, Alignment

	wb = Workbook()
	ws = wb.active
	ws.title = sheet_name[:31]

	if not rows:
		wb.save(output_path)
		return output_path

	headers = list(rows[0].keys())
	header_fill = PatternFill(start_color='1F497D', end_color='1F497D', fill_type='solid')
	header_font = Font(color='FFFFFF', bold=True)

	for col_idx, header in enumerate(headers, 1):
		cell = ws.cell(row=1, column=col_idx, value=header)
		cell.fill = header_fill
		cell.font = header_font
		cell.alignment = Alignment(horizontal='center')

	for row_idx, row in enumerate(rows, 2):
		for col_idx, header in enumerate(headers, 1):
			ws.cell(row=row_idx, column=col_idx, value=row.get(header, ''))

	for col in ws.columns:
		max_len = max((len(str(c.value or '')) for c in col), default=10)
		ws.column_dimensions[col[0].column_letter].width = min(max_len + 4, 50)

	wb.save(output_path)
	return output_path


def generate_document(
	format: str,
	content: str,
	title: str,
	output_path: str,
	rows: list[dict] | None = None,
	slides: list[dict] | None = None,
	sheet_name: str = 'Sheet1',
) -> str:
	"""Generate a document in the requested format. Returns the output path."""
	os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
	fmt = format.lower().lstrip('.')
	if fmt == 'docx':
		return _docx(content, title, output_path)
	elif fmt == 'pdf':
		return _pdf(content, title, output_path)
	elif fmt == 'pptx':
		return _pptx(content, title, output_path, slides=slides)
	elif fmt == 'xlsx':
		return _xlsx(rows or [], sheet_name, output_path)
	else:
		raise ValueError(f'Unsupported format: {format!r}. Use docx, pdf, pptx, or xlsx.')
