# capabilities/rfp_assembler.py
"""
Atomic capability: assemble all proposal sections into a single markdown document.
Writes output to data/rfp_responses/<id>/ and opens in neditor.
"""

import json
import re
import time
from pathlib import Path
from core.ai_engine import AIModel

from core.bundle import writable_data_dir as _wdd
_OUTPUT_DIR = _wdd() / 'rfp_responses'

_SECTION_ORDER = [
	'executive_summary',
	'technical_approach',
	'management_plan',
	'past_performance',
	'personnel',
	'pricing_narrative',
	'corporate_capabilities',
]


class RFPAssembler:
	def __init__(self, ai_engine: AIModel):
		self.ai_engine = ai_engine

	def assemble(
		self,
		sections: dict | str = '',
		compliance_matrix: list | str = '',
		rfp_title: str = 'RFP Response',
		rfp_id: str = '',
		style_guide: str = '',
	) -> dict:
		"""
		Assemble proposal sections into a markdown document and save to disk.

		Args:
			sections:          Dict {section_name: {content, word_count, ...} or str}.
			compliance_matrix: Compliance matrix list.
			rfp_title:         RFP title for the document header.
			rfp_id:            Optional RFP tracker ID for output directory naming.
			style_guide:       Style guide content for final review.

		Returns:
			{document_md, filename, word_count, section_index, output_path, neditor_opened}
		"""
		if isinstance(sections, str):
			try:
				sections = json.loads(sections)
			except Exception:
				sections = {'content': sections}

		# Build ordered document
		parts = [f'# {rfp_title}\n\n*Generated by Thuon — {time.strftime("%Y-%m-%d %H:%M")}*\n']
		section_index = []
		total_words   = 0

		for sec_name in _SECTION_ORDER:
			if sec_name not in sections:
				continue
			sec = sections[sec_name]
			content = sec.get('content', str(sec)) if isinstance(sec, dict) else str(sec)
			words   = sec.get('word_count', len(content.split())) if isinstance(sec, dict) else len(content.split())
			heading = sec_name.replace('_', ' ').title()
			parts.append(f'\n## {heading}\n\n{content}\n')
			section_index.append({'section': heading, 'word_count': words})
			total_words += words

		# Append compliance matrix as appendix
		if compliance_matrix:
			matrix = compliance_matrix if isinstance(compliance_matrix, list) else []
			parts.append('\n## Appendix A: Compliance Matrix\n\n')
			parts.append('| Req ID | Requirement | Type | Response Location | Status |\n')
			parts.append('|--------|------------|------|-------------------|--------|\n')
			for item in (matrix if isinstance(matrix, list) else []):
				if isinstance(item, dict):
					parts.append(
						f"| {item.get('req_id','')} | {item.get('text','')[:80]} | "
						f"{item.get('type','')} | {item.get('response_location','')} | "
						f"{item.get('status','')} |\n"
					)

		document_md = ''.join(parts)

		# Save to disk — sanitize rfp_id to prevent path traversal
		raw_name    = rfp_id or f'rfp_{time.strftime("%Y%m%d_%H%M%S")}'
		folder_name = re.sub(r'[^\w\-]', '_', raw_name)[:80]
		out_dir     = (_OUTPUT_DIR / folder_name).resolve()
		if not str(out_dir).startswith(str(_OUTPUT_DIR.resolve())):
			out_dir = _OUTPUT_DIR / f'rfp_{time.strftime("%Y%m%d_%H%M%S")}'
		out_dir.mkdir(parents=True, exist_ok=True)
		filename    = re.sub(r'[^\w\- ]', '', rfp_title)[:60].strip().replace(' ', '_') + '.md'
		out_path    = out_dir / filename
		out_path.write_text(document_md, encoding='utf-8')

		# Write to Obsidian if configured
		try:
			from core.obsidian_bridge import get_obsidian_bridge
			get_obsidian_bridge().write_rfp(rfp_title, document_md)
		except Exception:
			pass

		# Open in neditor
		neditor_opened = False
		try:
			from core.neditor_bridge import get_neditor_bridge
			neditor_opened = get_neditor_bridge().open(str(out_path), {'rfp_title': rfp_title})
		except Exception:
			pass

		return {
			'document_md':     document_md,
			'filename':        filename,
			'word_count':      total_words,
			'section_index':   section_index,
			'output_path':     str(out_path),
			'neditor_opened':  neditor_opened,
		}
